### ISSUE TITLE
Divide by 0 error with Mechanical User in ExtraUtilities2

### ISSUE THREAD

**Issue by dsevillamartin** [RicardoTheCoder/MiniMoos#30]
- [x] I am using a release version of the mod
- [x] I have mods that integrate with this installed:
     - [x] Tinker's Construct
     - [x] Mine Factory Reloaded
     - [x] Mine Addons
     - [ ] Moo Fluids
     - [x] Waila
     - [x] Avaritia
- [x] I also have other mods installed
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## Additional Information
- Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [x] Java 8
- Minecraft Version:
     - [x] 1.10.2

## Issue Description

Using this in Foolcraft v2.9.1. I summoned in a Mini Moo over a Mechanical User, and then moved over the mechanical user as well. My world crashed with an error, and I can't open it anymore. However, this hasn't happened before, not until yesterday, when I updated it and used some Thaumcraft (although nothing to interfere with the mechanical user).

## Reproduce Steps

Not sure.

## Additional Information

```java
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.bucket@0. Method:ENTITY  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:289) ~[TileUse.class:?]
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93) ~[TileAdvInteractor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.ricardothecoder.minimoos.entities.EntityFluidMoo.func_184645_a(EntityFluidMoo.java:412) ~[EntityFluidMoo.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1403) ~[sg.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161) ~[zs.class:?]
	at com.rwtema.extrautils2.compatibility.CompatHelper.interactOn(CompatHelper.java:80) ~[CompatHelper.class:?]
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:280) ~[TileUse.class:?]
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93) ~[TileAdvInteractor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by IRicTheCoder** [comment]
@datitisev Hi there, I'm sorry for the late response. I will look into this and fix it on the next version for 1.10, it should also be fixed the upcoming version for 1.12.

It is taking a lot longer then I wanted to fix these problems and update the mod cause I have been handling both work and personal issues. Sorry for the inconvenience.

I will get back to you as soon as I have a fix for the problem, Thanks

**Comment by dsevillamartin** [comment]
@RicardoTheCoder No problem!

I understand people have their own lives and personal issues.
Glad you'll work on a fix, though. 🙂
