### ISSUE TITLE
Game & Server crash when using Mini Moo in Safari in Auto-Spawner (MineFactory)

### ISSUE THREAD

**Issue by Ghrane** [RicardoTheCoder/MiniMoos#7]
- [X] I am using a release version of the mod
- [X] I have mods that integrate with this installed:
     - [X] Tinker's Construct
     - [X] Mine Factory Reloaded
     - [X] Mine Addons
     - [X] Moo Fluids
     - [X] Waila
- [X] I also have other mods installed
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)

## Additional Information
- [X] Java Version:
     - [ ] Java 6
     - [ ] Java 7
     - [X] Java 8
- [X] Minecraft Version:
     - [X] 1.10.2

## Issue Description
My local server Crashed when I used MineFactory's Safari Net (Reusable) with a Essence MiniMoo cow and used that safari net to make Exact copies or spawns with MineFactory's Auto-Spawner. In the first place it spawned invisible MiniMoos, you could hear them walk around and hear them moo, but they were not there, this was during the random spawning of the minimoos, once I clicked 'Spawn Exact Copy' the server crasht right away.
When I tried to reboot the server, it worked fine untill I joined the server, my base got loaded and the server crashed right away.
So I copied the world to my singleplayer, see if I could delete the Spawner, but then my whole game crashed. Luckily I got a backup, otherwise this world would've been doomed and corrupted.

Version: 1.10.2-12.18.3.2422-universal

Foolcraft (2) version 2.2
## Reproduce Steps
* Load up a world with the FoolCraft 2.2 modpack.
* Spawn in a Auto-Spawner by MineFactory, give it Power and put some Essence in it.
* Get a MineFactory Safari Net (Reusable) and capture a MiniMoo, put this Safari Net into the Spawner.
* Wait till a MiniMoo spawns.
* Select the option "Spawn Exact Copy" in the Auto-Spawner
* Boom, crash.

## Additional Information

Description: Exception in server tick loop

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:880)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:230)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:69)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:132)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:482)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:371)
	at net.minecraft.entity.EntityTracker.func_180245_a(EntityTracker.java:319)
	at net.minecraft.entity.player.EntityPlayerMP.func_175135_B(EntityPlayerMP.java:1190)
	at net.minecraft.entity.player.EntityPlayerMP.func_71016_p(EntityPlayerMP.java:1053)
	at com.rwtema.extrautils2.items.ItemAngelRing$PlayerPowerAngelRing.update(ItemAngelRing.java:168)
	at com.rwtema.extrautils2.power.player.PlayerPowerManager.tick(PlayerPowerManager.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_781_PlayerPowerManager_tick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.ricardothecoder.minimoos.entities.EntityFluidMoo.writeSpawnData(EntityFluidMoo.java:470)
	at net.minecraftforge.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:216)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:42)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:32)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 24 more

**Comment by IRicTheCoder** [comment]
@Ghrane This as been fixed on version 1.1.1 of the mod, which is already present on version 2.3 of FoolCraft. Using the same world on the version 2.3 of FC should also regenerate your world and remove unwanted or bugged cows.

As for Exact Copies, they are disabled to ensure that there aren't bugged cows being spawned, those invisible cows should be an artifact from the client's slave world, and should be gone upon relog.

I'm also looking into a way to allow Exact Copies without generating bugged cows.

Please either update your mod to 1.1.1 or update your foolcraft modpack to version 2.3 (Make sure the update deletes the older version).

**Comment by Ghrane** [comment]
I have done both the updates now.
Tho I have already overwriten my world with a 1 day old backup, so I cannot confirm the fix yet.
But I'll trust your words.
I couldn't find any update log file, so I thought atleast share the problem.
Good to know it got fixed!

**Comment by IRicTheCoder** [comment]
@Ghrane No problem and thanks for placing an issue, specially here instead of in foolcraft as it is easier for me to read it and get on fixing it.

I have forced a corrupt save file just to test if it would regenerate, and it did so it should be fine. If you experience any other problems or if the crash happens again, please tell me about it so I could check it.

**Comment by Ghrane** [comment]
Will do!
